name: 'Django Security Check'
description: 'Helps find and remediate common security vulnerabilities in your Django application.'
author: 'victoriadrake'
branding:
  icon: 'shield'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
